Authentication and Authorization code
ValidationError: Email: Path Email is required is still an error when attempting to post a new user from postman